missing_to_phrase:
  aftertaste:
    - "カラメルの香りがふわっと鼻に抜ける感じ"
    - "卵のコクがあとからじんわり残るよ"
  firmness:
    - "ゼラチン強めの“しっかり”食感"
    - "スプーンがすっと立つ固さ"
  temp_curve:
    - "口の中で温度がゆっくり溶けていく感じ"
    - "冷たさが中心から外へほどける"
