interest:
  tau_f: 1.0
  fixation_ref_ms: 900.0
  saccade_ref_hz: 3.0
  blink_ref_hz: 1.6
  alpha: 0.6
  beta: 0.3
  gamma: 0.25
  eta: 0.2
  theta_focus: 0.55
  hysteresis: 0.07
  fatigue_blink_hz: 2.5
group:
  theta: 0.5
  dwell_tau: 1.2
  weights:
    self: 1.0
